# Generated by Django 3.2.20 on 2023-09-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_table_is_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
