# Generated by Django 3.2.20 on 2023-07-28 15:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='€', max_length=5)),
                ('dietary_tags', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(default='static/images/dish-1.jpg', max_length=255, verbose_name='image')),
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
