# Generated by Django 3.2.20 on 2023-07-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
