# Generated by Django 3.2.20 on 2023-07-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_customer_onlinetablereservation_operatinghours_reservation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='Guest', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
