# Generated by Django 3.2.20 on 2023-07-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_dietarypreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='dietary_preferences',
            field=models.ManyToManyField(blank=True, to='booking.DietaryPreference'),
        ),
    ]
