# Generated by Django 3.2.20 on 2023-07-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
