# Generated by Django 3.2.20 on 2023-07-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_reservation_number_of_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('CF', 'Confirmed'), ('CL', 'Cancelled')], default='PD', max_length=2),
        ),
    ]
