# Generated by Django 3.2.20 on 2023-08-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_staffuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffUser',
        ),
    ]
