# Generated by Django 3.2.20 on 2023-08-29 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0012_alter_task_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='staff_or_manager',
            field=models.CharField(choices=[('staff', 'Staff'), ('manager', 'Manager')], default='staff', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='booking.reservation'),
        ),
    ]
