# Generated by Django 3.2.20 on 2023-08-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20230829_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('CF', 'Confirmed'), ('CL', 'Cancelled')], default='PD', max_length=8),
        ),
    ]
