# Generated by Django 3.2.20 on 2023-09-04 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
        ('booking', '0022_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_manager.table'),
        ),
    ]
